# Generated by Django 4.1.1 on 2022-09-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_favoritephoto_favoritealbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritealbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.UUID('68bd7d25-64cc-4786-a7f3-3cffd1b99a7d'))),
                ('expires', models.DateTimeField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.photo')),
            ],
        ),
    ]
