# Generated by Django 4.1.1 on 2022-09-24 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_favoritealbum_user_phototoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototoken',
            name='expires',
            field=models.DateTimeField(default=webapp.models.epire_date),
        ),
        migrations.AlterField(
            model_name='phototoken',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='webapp.photo'),
        ),
        migrations.AlterField(
            model_name='phototoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('4da55ae7-f55e-4267-8552-341b62c96478')),
        ),
    ]
