# Generated by Django 4.1.1 on 2022-09-24 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_phototoken_expires_alter_phototoken_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='phototoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b71aa79a-81f0-46df-9485-e5e8463cf469'), primary_key=True, serialize=False),
        ),
    ]
