# Generated by Django 4.1.1 on 2022-09-24 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_phototoken_token_alter_phototoken_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27df6572-bbde-407b-a958-1c5471cc98db'), primary_key=True, serialize=False),
        ),
    ]
